---
title: "Assignment I pt. IV"
author: "Dana Jensen"
date: "October 5, 2017"
output: html_document
---
---
                          "COMPLETE"
---
```{r}
#prelude 
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/Dana/Desktop/METHODS III/assignmentIpt.IV")
library(pacman)
p_load(dplyr, ggplot2, lmerTest,simr, MASS)
train = read.csv("df_train.csv")
```
### Exercise 1
```{r}
  ## How much power does your study have (if your model estimates are quite     right)?
  ## - Load your dataset, fit your favorite model, assess power for your main   effects and interactions of interest.
  ## - Report the power analysis and comment on what you can (or cannot) use    its estimates for.

#Strike a pose. Vogue.
model = lmer(CHI_MLU ~ VISIT + Diagnosis +(1+VISIT | SUBJ),train, REML = FALSE)
summary(model)
#question: what units are mlu recorded in? what does an effect of 0.23 mean then?

#I've got the power
pv = powerSim(model,fixed("VISIT"),nsim=10)
pv #100%, 69.15 - 100
pd = powerSim(model,fixed("Diagnosis"),nsim=10)
pd #40%, 12.16 - 73.76

```
### Exercise 2
```{r}

## How would you perform a more conservative power analysis?
  ## - Identify and justify a minimum effect size for each of your relevant effects

##Finding the smallest effect size with the model

#visit = 0.23, Diagnosis = 0.29 normally
fixef(model)["VISIT"] <- 0.0693 # but are we interested in 0.0693??
pv1 = powerSim(model,fixed("VISIT"),nsim=10)
pv1 #80% (44.39, 97.48)

fixef(model)["DiagnosisTD"] <- 0.43
pd1 = powerSim(model,fixed("Diagnosis"),nsim=10)
pd1 #80% (44.39, 97.48)

  ## - Take the model from exercise 1 and replace the effects with the minimum   effect size that you'd accept.

##Deciding the lowest acceptable effect size

# "Okay honey, I'm changing the effect sizes now!"
fixef(model)["VISIT"] <- 0.20
pv2 = powerSim(model,fixed("VISIT"),nsim=10)
pv2

fixef(model)["DiagnosisTD"] <- 0.43
pd2 = powerSim(model,fixed("Diagnosis"),nsim=10)
pd2

  ## - Assess the power curve by Child.ID, identifying an ideal number of participants to estimate each effect

##Power curve that shit
pcv1= powerCurve(model, fixed("VISIT"),along="SUBJ", nsim=10)
pcv1

pcv2<-powerCurve(model, fixed("DiagnosisTD"),along="SUBJ", nsim=10)
pcv2 #gives 0 values

  ## - Report the power analysis and comment on what you can (or cannot) use    its estimates for.
```
### Exercise 3
```{r}

  ## Assume you have only the resources to collect 30 kids (15 with ASD and 15   TDs). Identify the power for each relevant effect and discuss whether it's    worth to run the study and why.

#Riccardo's function to simulate participants
createNewData <- function (participants,visits,model){
  # participants is the number of subjects
  # visits is the number of visits
  fe <- fixef(model)
  Intercept <- fe[1] #intercept
  bVisit <- fe[2] #visit
  bDiagnosis <- fe[3] #diagnosis
  # bVisitDiagnosis <- fe[4] #visit diagnosis interaction
  vc<-VarCorr(model) # variance component
  sigmaSubject <- as.numeric(attr(vc[[1]],"stddev")[1]) # random intercept by   subject
  sigmaVisit <- as.numeric(attr(vc[[1]],"stddev")[2]) # random slope of visit   over subject
  sigmaResiduals <- as.numeric(attr(vc,"sc"))
  sigmaCorrelation <- as.numeric(attr(vc[[1]],"correlation")[2])
  d=expand.grid(Visit=1:visits,SUBJ=1:participants)
  # Randomly sample from a binomial (to generate the diagnosis)
  condition <- sample(rep(0:1, participants/2))
  d$Diagnosis<-condition[d$SUBJ]
  d$Diagnosis[is.na(d$Diagnosis)]<-1
  Sigma.u<-matrix(c(sigmaSubject^2,
                    sigmaCorrelation*sigmaSubject*sigmaVisit,
                    sigmaCorrelation*sigmaSubject*sigmaVisit,
                    sigmaVisit^2),nrow=2)
  ## generate new fake participants (column1=RandomIntercept,                   column2=RandomSlope)
  u<-mvrnorm(n=participants,
             mu=c(0,0),Sigma=Sigma.u)
  ## now generate fake data:
  ### the outcome is extracted from a gaussian with the solution to the         model's equation as mean and the residual standard deviation as standard      deviation 
  d$CHI_MLU <- rnorm(participants*visits,
                     (Intercept+u[,1]) +
                     (bVisit+u[,2])*d$Visit + 
                     bDiagnosis*d$Diagnosis ,sigmaResiduals)  
  return(d)
}

#let's see what happens
d<-createNewData(30,6,model)

#just making sure ASD/TD are equal
length(d$Diagnosis=='0')
length(d$Diagnosis=='1')

#now let's start
model1 = lmer(CHI_MLU ~ Visit + Diagnosis +(1+Visit | SUBJ),d, REML = FALSE)
pv3 = powerSim(model1,fixed("Visit"),nsim=10)
pv3
pd3 = powerSim(model1,fixed("Diagnosis"),nsim=10)
pd3

#or maybe use my pre-determined effect sizes
fixef(model1)["VISIT"] <- 0.20
pv4 = powerSim(model,fixed("VISIT"),nsim=10)
pv4

fixef(model1)["DiagnosisTD"] <- 0.43
pd4 = powerSim(model,fixed("Diagnosis"),nsim=10)
pd4
```